App_Blog/urls.py
from django.urls import path
from . import views

app_name = 'App_blog'
urlpatterns = [
     path('', views.BlogListView.as_view(), name='blog_list'),
     path('write/', views.CreateBlog.as_view(), name='create_blog'),
     path('details/<str:blog_title>', views.blog_details, name='blog_details'),
     path('liked/<pk>/', views.liked, name='liked_post'),
     path('unliked/<pk>/', views.un_liked, name='un_liked'),
     path('myblogs/', views.MyBlogs.as_view(), name='my_blogs'),
     path('edit/<pk>/', views.UpdateBlogs.as_view(), name='edit_blog'),
]

App_Login/urls.py
from django.urls import path
from .import views

app_name = 'App_Login'

urlpatterns = [
    path('sign_up/', views.sign_up, name='sign_up'),
    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('change_profile/', views.profile_change, name='change_profile'),
    path('password/', views.user_password_change, name='password_change'),
    path('add_profile_pic/', views.add_profile_pic, name='add_profile_pic'),
    path('change_profile_pic/',views.change_profile_pic, name='change_profile_pic'),

]

Blog_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('App_Login.urls')),
    path('blog/', include('App_Blog.urls')),
    path('', views.index, name='index'),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Login/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user_profile')
    profile_pic = models.ImageField(upload_to='profile_pic')
    contact_info = models.CharField(max_length=200)

App_Login/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login, logout, authenticate
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .Sign_up_forms import SignUpForm, UserProfileChange, UserProfilePic
from .models import UserProfile
# Create your views here.


def sign_up(request):
    form = SignUpForm()
    registered = False
    if request.method == 'POST':
        form = SignUpForm(data=request.POST)
        if form.is_valid():
            form.save()
            registered = True
    diction = {'form': form, 'registered': registered}
    return render(request, 'App_Login/sign_up.html', context=diction)


def login_page(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
    return render(request, 'App_Login/login.html', context={'form': form})


@login_required
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('App_Login:login'))


@login_required
def profile(request):
    return render(request,'App_Login/profile.html', context={})

@login_required
def profile_change(request):
    current_user = request.user
    form = UserProfileChange(instance=current_user)
    if request.method == 'POST':
        form = UserProfileChange(request.POST, instance=current_user)
        if form.is_valid():
            form.save()
            form = UserProfileChange(request.POST, instance=current_user)
            return HttpResponseRedirect(reverse('App_Login:profile'))
    dict = {'form': form}
    return render(request, 'App_Login/change_profile.html', context=dict)


@login_required
def user_password_change(request):
    current_user = request.user
    form = PasswordChangeForm(current_user)
    changed = False
    if request.method == 'POST':
        form = PasswordChangeForm(current_user, data=request.POST)
        if form.is_valid():
            form.save()
            changed = True
    return render(request, 'App_Login/change_password.html', context={'form': form, 'changed': changed})

@login_required
def add_profile_pic(request):
    form = UserProfilePic()
    if request.method == 'POST':
        form = UserProfilePic(request.POST, request.FILES)
        if form.is_valid():
            user_obj = form.save(commit=False)
            user_obj.user = request.user
            user_obj.save()
            return HttpResponseRedirect(reverse('App_Login:profile'))
    return render(request, 'App_Login/profile_pic_add.html', context={'form': form})

@login_required
def change_profile_pic(request):
    form = UserProfilePic(instance=request.user.user_profile)
    if request.method == 'POST':
        form = UserProfilePic(request.POST, request.FILES, instance=request.user.user_profile)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('App_Login:profile'))
    return render(request, 'App_Login/profile_pic_add.html', context={'form': form})

templates/App_Login/change_password.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Change Password {% endblock %}
{% block body_block %}
    {% if changed %}
        <div class="alert alert-success">Password Change Successfully</div>
    {% endif %}
        <form method="POST">
        {{ form|crispy }}
        {% csrf_token %}<br>
        <button type="submit" class="btn btn-warning btn-sm">Change Password</button>
        </form>
{% endblock %}

templates/App_Login/change_profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %}Change Profile{% endblock %}
{% block body_block %}
    <form method="POST">
      {{ form|crispy }}
    {% csrf_token %}
    <button type="submit" class="btn btn-warning btn-sm">Change</button>
    </form>
{% endblock %}

templates/App_Login/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Login {% endblock %}
{% block body_block %}
    <form method="POST">
    {% csrf_token %}
     {{ form|crispy }}
    <br>
    <input type="submit" name="submit" value="Log In" class="btn btn-success">
    </form>
{% endblock %}

templates/App_Login/profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Profile {% endblock %}
{% block body_block %}
    <h3>{{ user.username }} Profile</h3><br>
    {% if user.user_profile %}
        <img src="/media/{{ user.user_profile.profile_pic }}" width="200" height="200" class="rounded-circle">
        <br><br><a href="{% url 'App_Login:change_profile_pic' %}" class="btn btn-info btn-sm">Change Profile Picture</a>
    {% else %}
        <img src="/media/profile_pic/avatar-male.jpg" width="200" height="200" class="rounded-circle">
        <br><br><a href="{% url 'App_Login:add_profile_pic' %}" class="btn btn-info btn-sm">Change Profile Picture</a>
    {% endif %}
    <hr>
    <p>UserName: {{ user.username }}</p>
    <p>Email: {{ user.email }}</p>
    <p>Name: {{ user.first_name }} {{ user.last_name }}</p>
    <br>
    <a href="{% url "App_Login:change_profile" %}" class='btn btn-warning btn-sm'>Change Your Profile</a>
{% endblock %}

templates/App_Login/profile_pic_add.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %}Add New Profile Picture{% endblock %}
{% block body_block %}
    <form method="POST" enctype="multipart/form-data">
    {{ form|crispy }}
    {% csrf_token %}
        <br>
    <button type="submit" class="btn btn-success btn-sm">Save</button>
    </form>
{% endblock %}

templates/App_Login/sign_up.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %}Create A New Account {% endblock %}
{% block body_block %}
{% if registered %}
        <div class="alert alert-success">Account Create Successfully !!<br><a href="{% url 'App_Login:login' %}">Login Here</a></div>
    {% else %}
        <h3 style="padding-top: 20px">Create New Account</h3>
        <form method="POST" class="container" style="padding-top: 20px">
           {{ form|crispy }}
               {% csrf_token %}
            <br>
          <button type="submit" class="btn btn-success btn-sm">Create Account</button>
        </form>
        <br>
        <p>Already Have An Account ? <a href="{% url 'App_Login:login' %}">Login Here</a> </p>
    {% endif %}
{% endblock %}