App_Blog/urls.py
from django.urls import path
from . import views

app_name = 'App_blog'
urlpatterns = [
     path('', views.BlogListView.as_view(), name='blog_list'),
     path('write/', views.CreateBlog.as_view(), name='create_blog'),
     path('details/<str:blog_title>', views.blog_details, name='blog_details'),
     path('liked/<pk>/', views.liked, name='liked_post'),
     path('unliked/<pk>/', views.un_liked, name='un_liked'),
     path('myblogs/', views.MyBlogs.as_view(), name='my_blogs'),
     path('edit/<pk>/', views.UpdateBlogs.as_view(), name='edit_blog'),
]

App_Login/urls.py
from django.urls import path
from .import views

app_name = 'App_Login'

urlpatterns = [
    path('sign_up/', views.sign_up, name='sign_up'),
    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('change_profile/', views.profile_change, name='change_profile'),
    path('password/', views.user_password_change, name='password_change'),
    path('add_profile_pic/', views.add_profile_pic, name='add_profile_pic'),
    path('change_profile_pic/',views.change_profile_pic, name='change_profile_pic'),

]

Blog_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('App_Login.urls')),
    path('blog/', include('App_Blog.urls')),
    path('', views.index, name='index'),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <!-- jQuery library -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <!-- Popper JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <!-- Latest compiled JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <title>{% block title_block %} Blogs {% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-info">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'index' %}"><img src="/media/logo.png" width="25px"></a>
        </li>
          {% if user.is_authenticated %}
               <div class="nav-item dropdown">
                    <a class="nav-link dropdown-toggel" href="" id="navbardrop" data-toggle="dropdown">@{{ user.username }}</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href='{% url 'App_blog:create_blog' %}'>Create A New Blog</a>
                        <a class="dropdown-item" href='{% url 'App_blog:my_blogs' %}'>My Blogs</a>
                        <a class="dropdown-item" href='{% url 'App_Login:profile' %}'>Profile</a>
                        <hr>
                        <a class="dropdown-item" href='{% url 'App_Login:logout' %}'>Log Out</a>
                    </div>
               </div>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'App_Login:sign_up' %}">Sign Up</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href='{% url 'App_Login:login' %}'>Log In</a>
            </li>
              <li class="nav-item">
              <a class="nav-link" href='#'></a>
            </li>
          {% endif %}
      </ul>
</nav>
<div class="container" style="padding-top: 20px">
    {% block body_block %}

    {% endblock %}
</div>
</body>
</html>